withastro/roadmap

active-rfcs/add-prettier-plugin-to-vscode-extension.md, active-rfcs/add-test-tool-for-astro-components.md, active-rfcs/replace-prism-with-shiki.md, active-rfcs/support-draft-markdown-posts.md, active-rfcs/support-exports-from-astro-components.md, active-rfcs/support-html-files.md
This adds the [6 accepted legacy RFCs](https://github.com/withastro/astro/issues?q=is%3Aissue+is%3Aopen+%22RFC%3A%22+in%3Atitle+) from https://github.com/withastro/astro. These RFCs do not meet the requirements of the current RFC process, but they were accepted before the current process was created.
Each legacy RFC includes a notice at the top, with a link to the current RFC standards.
`````markdown
<p align="center"><strong>⚠️⚠️⚠️ Legacy RFC Disclaimer ⚠️⚠️⚠️
<br />This RFC does not meet the requirements of the current RFC process.
<br />It was accepted before the current process was created.
<br /><a href="https://github.com/withastro/rfcs#readme">Learn more about the RFC standards.</a>
</strong></p>
---
`````
=> Add accepted legacy RFCs

active-rfcs/0000-finalize-head-body.md
- Start Date: 2021-11-30
Finalize behavior around `<head>`, `<body>`, `<html>`, and `<!DOCTYPE html>` elements in Astro component templates.
- [Full Rendered Proposal](https://github.com/withastro/rfcs/blob/FredKSchott-patch-2/active-rfcs/0000-finalize-head-body.md)
=> Finalize <head>, <body>, <html>

active-rfcs/0000-style-script-behavior.md
- Start Date: 2021-12-09
- Status: Accepted
- Previous discussion: #12 
Finalize the component styling & scripting behavior for v1.0. Documents existing behavior and adds 2-3 new restrictions to prevent bugs.
```
<style>
@import './dep.css'; /* Vite imports supported, including npm packages! */
h1 { color: red; }
</style>
<style global>
/* Same as <style>, but styles are applied globally to the page. */
body { padding: 5px; }
</style>
<script>
console.log('included as-is in the final HTML page output.')
</script>
<script hoist>
import cowsay from 'cowsay';
console.log(cowsay('I am bundled with the rest of the website JS!'));
</script>
<h1>Hello!</h1>
```
- [Full Rendered Proposal](https://github.com/withastro/rfcs/blob/style-script-rfc/active-rfcs/0000-style-script-behavior.md)
=> finalize v1.0 component script and style behavior

active-rfcs/0000-style-unification.md
- Start Date: 2021-12-14
Clean up and finalize how CSS is used and referenced in an Astro project.
- [Full Rendered Proposal](  https://github.com/withastro/rfcs/blob/FredKSchott-patch-1/active-rfcs/0000-style-unification.md)
=> Style usage unification for Astro v1.0

active-rfcs/0000-build-performance.md
- Start Date: 2021-12-13
Deprecate features of Astro that are not compatible with SSR and also degrade build performance on larger sites. Replace these features with static alternatives.
- [Full Rendered Proposal](https://github.com/withastro/rfcs/blob/build-performance-rfc/active-rfcs/0000-build-performance.md)
=> Improved Build Performance

active-rfcs/0000-relative-url-scheme.md
- Start Date: 2021-12-20
This proposal seeks to improve source-relative URL support in Astro files.
- [Full Rendered Proposal](https://github.com/withastro/rfcs/blob/jn.relative-url-scheme-proposal/active-rfcs/0000-relative-url-scheme.md)
=> Proposal: Support a `local:` attribute prefix

active-rfcs/0000-scoped-css-with-preserved-specificity.md
- Start Date: 2022-01-04
This proposes Astro preserve specificity in scoped CSS, consistent with the specificity in global CSS.
Astro currently adds an additional class to all elements and selectors, increasing specificity from `O+1` to `O(1)+1`.
Astro can prevent this specificity increase by wrapping the scoping mechanism in a `:where()` CSS pseudo-class.
This RFC was previously submitted in [withastro/astro#1909](https://github.com/withastro/astro/issues/1909), but it was not reviewed before the process was changed. Neither this proposal or the current functionality were covered in the [Style Unification Proposal](https://github.com/withastro/rfcs/blob/main/active-rfcs/0000-style-unification.md). This proposal uses the new format, and is submitted to finalize this …
=> Preserve specificity in scoped CSS

proposals/api-route-signature.md
- Start Date: 2022-04-25
Change the signature for API routes into a single `APIContext` argument, allowing you to use destructing to get the properties you want:
```js
export async function get({ params, request }) {
if(!request.headers.has('cookie')) {
return new Response(null, {
status: 301,
headers: {
Location: '/'
}
});
}
// ...
}
```
- [Full Rendered Proposal](https://github.com/withastro/rfcs/blob/b636579ce4e6781c119433147eb93e0f9db8c049/proposals/api-route-signature.md)
=> API route proposed changes

proposals/astro-response.md
- Start Date: 2022-04-29
Adds an `Astro.response` object as a way to modify response properties, such as the `status`, `statusText`, and `headers`. The object mirrors the structure of the standard [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) but is a plain object, to allow modifying properties that are readonly on Response.
- [Full Rendered Proposal](https://github.com/withastro/rfcs/blob/astro-response/proposals/astro-response.md)
- [Standard Response object](https://developer.mozilla.org/en-US/docs/Web/API/Response)
=> Astro.response, a way to modify response properties

proposals/0000-deprecate-markdown-component.md
- Start Date: 2022-04-29
Hey everyone! We (the core maintainers, @withastro/maintainers-core) have been discussing the `<Markdown />` component a lot over the last few days, and have made the decision to deprecate the `<Markdown />` component ahead of our v1.0 release. **It will continue to be available as a non-core, user-land npm package (`@astrojs/markdown`) post v1.0.**
This is a bit of an odd RFC in that it's driven by a need to fix a buggy experience, and not talking through the best way to add something new. We've been discussing this on the core team on-off for a few weeks now, and have already reached informal consensus within the group, but I would still like to share this with our larger maintainer community for feedback during the next RFC call.
For more …
=> Deprecate the `<Markdown>` Component

proposals/0022-frontmatter-plugins.md
- Start Date: 2022-05-20
I suggest adding a new `markdown.frontmatterPlugins` config option to unlock some usecases and improve developer experience.
- https://github.com/sylvinus/rfcs/blob/main/proposals/0022-frontmatter-plugins.md
- https://github.com/withastro/astro/pull/3411
=> Add a new markdown.frontmatterPlugins config option

proposals/0023-inject-route.md
- Start Date: 2022-06-01
- Status: Ready
Proposes a `injectRoute` API to the integrations `'astro:config:setup'` hook, similar to `injectScript`. This API would allow integrations to add routes to projects, that ship have prebuild, plug-n-play functionality, pages, or route handlers. For consumers of such integrations, this would allow highly plug-and-play like experiences for adding functionality.
- Full Rendered Proposal: https://github.com/thepassle/rfcs/blob/feat/inject-route/proposals/0023-inject-route.md
- Docs PR: https://github.com/withastro/docs/pull/704
- Implementation PR: https://github.com/withastro/astro/pull/3457
=> feat: add inject-route rfc

proposals/cookie-management.md
- Start Date: 2022-08-29
Provides a simpler API for getting and setting cookie values through a Map-like interface:
```astro
---
const prefs = Astro.cookies.get('prefs').json();
---
<body data-theme={prefs.darkMode ? 'dark' : 'light'}>
```
And setting:
```astro
---
Astro.cookies.set('prefs', { darkMode: true }, {
expires: '1 month'
});
---
```
- [Full Rendered Proposal](https://github.com/withastro/rfcs/blob/rfc-cookie-management/proposals/cookie-management.md)
=> Simplified cookie management

proposals/0026-component-interface.md, proposals/component-interface.md
- Start Date: 2022-09-12
Introduces a new interface called "Component" that is used to describe components. This unlocks the following benefits:
- Ability to document components
- (Future) Ability to type slots and possibly other things an Astro component could need in the future in one consolidated interface
- [Full Rendered Proposal](https://github.com/withastro/rfcs/blob/44eec52b148e57b0639fc7746a47f9eaa2819b73/proposals/component-interface.md)
=> RFC: Component interface

template.md
This is not a new RFC but a proposed change to the template.
It adds an explicit section on testing strategies. As Astro grows the cost of new features also grows. Knowing how a feature will be tested gives us greater confidence that the feature will be easy to maintain and fewer regressions will occur. This also forces the RFC creator to think through edge cases they might otherwise gloss over.
=> Add testing section to the RFC template

template.md
This is something that has become a pattern in official RFCs that I would like to standardize across all RFCs by breaking up the "Motivation" section.
Calling out an RFC's explicit Goals and Non-Goals help focus the conversation. Without this, often the "Motivation" section becomes more about story-telling and less about clear, explicit context setting. By calling these out and using a bulleted list format, it forces the RFC author to think through and verbalize what they are trying to accomplish with their RFC. 
While converting 1 section to 3 sections may look like adding more work, its intent is to cut down on the overall length of the RFC by encouraging the use of bulleted lists for some of the content that previously lived in "Motivation".
=> [META] Add Goals/Non-Goals to RFC template

proposals/0022-frontmatter-plugins.md
As per https://github.com/withastro/astro/pull/3411#issuecomment-1407671566
I threw in a docs link, which is non-standard (not part of the template), so maybe I should back that change out? Provided two links, the docs change a lot and aren't versioned, so seemed prudent to link to a specific commit as well.
=> `0022-frontmatter-plugins`: add PR etc.

proposals/cdn-support.md
This RFC adds CDN support through the `build.assetsPrefix` option. Allowing sites to fetch all assets from an external CDN.
- [Fully rendered proposal](https://github.com/withastro/roadmap/blob/7dd302e0134813f1de67637792883680de40d60d/proposals/cdn-support.md)
- [Stage 2 proposal](https://github.com/withastro/roadmap/issues/534)
- [Stage 1 proposal](https://github.com/withastro/roadmap/discussions/456)
=> CDN support

proposals/style-scoping.md
This RFC introduces a new `scopedStyleStrategy` option to re-enable class based scoping, preventing bugs associated with CSS ordering that occur with the current `where` based strategy.
- [Fully rendered proposal](https://github.com/withastro/roadmap/blob/51d7fd2fa42f7e23b11f904e03b63b5efc7b2770/proposals/style-scoping.md)
- [Stage 2 proposal](https://github.com/withastro/roadmap/issues/540)
- [Stage 1 proposal](https://github.com/withastro/roadmap/discussions/510)
=> Scoping RFC

README.md
Updates the language for how consensus works to match what we've been doing. Namely:
- Consensus is reached async during a final comment period.
- Rules here follow the governance voting rules.
- After the comment period the RFC is eligible for merging.
=> Specify a final comment period

proposals/html-minification.md
Provide an option in the config to compress the output HTML.
* [Full rendered proposal](https://github.com/withastro/roadmap/blob/fa80178362386418fcb73967d6ff27798847eea6/proposals/html-minification.md)
* [Stage 2 proposal](https://github.com/withastro/roadmap/issues/537)
* [Stage 1 proposal](https://github.com/withastro/roadmap/discussions/165)
=> HTML Minification RFC

proposals/0032-middleware-api.md
This RFC introduce a new middleware API in Astro
- [Fully rendered proposal](https://github.com/withastro/roadmap/blob/rfc/stage-3-middleware/proposals/0032-middleware-api.md)
- [Stage 2 proposal](https://github.com/withastro/roadmap/issues/531)
- Stage 1 proposal
- https://github.com/withastro/roadmap/discussions/469
- https://github.com/withastro/roadmap/discussions/174
=> Astro middleware

proposals/custom-client-directives.md
Support custom `client:` directives added by integrations
* [Full rendered proposal](https://github.com/withastro/roadmap/blob/custom-client-directives/proposals/custom-client-directives.md)
* [Stage 2 proposal](https://github.com/withastro/roadmap/issues/529)
* [Stage 1 proposal](https://github.com/withastro/roadmap/discussions/272)
=> Custom Client Directives

proposals/hybrid-rendering.md
Provide a `output: 'hybrid'` mode to allow static sites to opt-in certain pages to be dynamic (not prerendered).
* [Full rendered proposal](https://github.com/withastro/roadmap/blob/213cf99cd9ded5ac03b300366e79da21bb5f4332/proposals/hybrid-rendering.md)
* [Stage 2 proposal](https://github.com/withastro/roadmap/issues/539)
* [Stage 1 proposal](https://github.com/withastro/roadmap/discussions/455)
=> Hybrid rendering stage 3 proposal

proposals/redirects.md
Provide a `redirects` config option for specifying redirected pages. Provide good integration with adapters.
* [Full rendered proposal](https://github.com/withastro/roadmap/blob/redirects/proposals/redirects.md)
* [Stage 2 proposal](https://github.com/withastro/roadmap/issues/466)
* [Stage 1 proposal](https://github.com/withastro/roadmap/discussions/319)
=> Redirects RFC

proposals/fragments.md, proposals/partials.md
Add the ability to configure a page in the `pages` directory to be treated as a *fragment*. A fragment is a chunk of HTML that is not interpreted to be a page, so no head content or `doctype` are included.
- [Rendered RFC](https://github.com/withastro/roadmap/blob/fragments/proposals/partials.md)
- [Stage 2 Proposal](https://github.com/withastro/roadmap/issues/697)
- [Stage 1 Proposal](https://github.com/withastro/roadmap/discussions/266)
=> Partials RFC

proposals/middleware-in-integrations.md
Add the ability for integrations to define middleware on behalf of the application developer.
- [Rendered RFC](https://github.com/withastro/roadmap/blob/integration-middleware/proposals/middleware-in-integrations.md)
- [Stage 2 Proposal](https://github.com/withastro/roadmap/issues/709)
- [Stage 1 Proposal](https://github.com/withastro/roadmap/discussions/692)
=> Integration hooks for middleware

proposals/0041-i18n-routing.md
i18n routing support baked into Astro.
- [Rendered RFC](https://github.com/withastro/roadmap/blob/i18n-routing/proposals/0041-i18n-routing.md)
- [Stage 2 Proposal](https://github.com/withastro/roadmap/issues/701)
- [Stage 1 Proposal](https://github.com/withastro/roadmap/discussions/600)
=> i18n routing RFC

proposals/0045-i18n-routing.md
This PR addresses Bjorn's feedback in the PR https://github.com/withastro/roadmap/pull/734
Also, I changed the number of the file to be 45
=> chore: address feedback

proposals/0046-csrf-protection.md
CSRF - Cross-site Request forgery -  protection
- [Rendered RFC](https://github.com/withastro/roadmap/blob/feat/csrf-protection-rfc/proposals/0046-csrf-protection.md)
- [Stage 2 Proposal](https://github.com/withastro/roadmap/issues/811)
- [Stage 1 Proposal](https://github.com/withastro/roadmap/discussions/471)
=> rfc: CSRF protection

README.md
2 points of clarification:
- An RFC is more likely to move through stages if a maintainer is one of its champions (there can be multiple).
- The proposal author should be given a chance to volunteer as the champion.
=> Clarify champion selection

README.md
The process calls for RFC meetings, which we have not had formally in quite a while. This change brings those back and clarifies who can call for them.
=> Clarify RFC meetings

proposals/server-islands.md
Allow islands of server-rendered content that renders after the page load, allowing more cacheable pages.
```astro
<Avatar server:defer>
<div slot="fallback">Guest</div>
</Avatar>
```
- [Rendered RFC](https://github.com/withastro/roadmap/blob/server-islands/proposals/server-islands.md)
- [Stage 2 Proposal](https://github.com/withastro/roadmap/issues/945)
- [Stage 1 Proposal](https://github.com/withastro/roadmap/discussions/907)
=> Server Islands

proposals/0048-container-api.md
I created this PR because I did not find other way to do the inline suggestion on existing rfc PR
Also I feel that the discussion was already made pior to my change that is just a fix for a typo in text
The rfc solves the container api
- [Rendered RFC](https://github.com/Scot3004/roadmap/blob/3dac369cdfc6e41dee2909b9920c2a85b3b76483/proposals/0048-container-api.md)
=> fix typo on import loadRenderers instead of laodRenderers

proposals/0051-serialized-manifest.md
```js
import { trailingSlash } from "astro:config/client"
console.log(trailingSlash) // logs "never"
```
- [Rendered RFC](https://github.com/withastro/roadmap/blob/feat/serialised-config/proposals/0051-serialized-manifest.md)
- [Stage 2 Proposal](https://github.com/withastro/roadmap/issues/1099)
- [Stage 1 Proposal](https://github.com/withastro/roadmap/discussions/1070)
=> feat: serialised config
